/* Catálogo de charms de ASTÉRIA.
 *
 * Una entrada por variante real del taller: los nombres y las medidas salen
 * del tablero "CHARMS AND PIECES" y la foto es el recorte de cada pieza
 * (img/charms). `mm` es la medida real y `eje` dice a que lado corresponde
 * (largo, ancho o diametro): de ahi sale su tamano sobre la funda, medido
 * contra las medidas reales del iPhone elegido.
 *
 * Las letras no llevan foto a proposito: las del tablero estaban en baja
 * calidad, asi que se dibujan (campo `letra`) de la A a la Z en oro y plata.
 *
 * Nada de esto lleva precio: los precios viven en el panel, nunca aqui.
 */
window.ASTERIA_CHARMS = [
  { id: "p01", n: 1, nombre: "Ángel", eje: "largo", mm: 27, tono: "plata", cat: "Figuras", img: "img/charms/angel-plata.webp", proporcion: 0.577 },
  { id: "p02", n: 2, nombre: "Pez plata", eje: "ancho", mm: 30, tono: "plata", cat: "Mar", img: "img/charms/pez-plata-plata.webp", proporcion: 1.478 },
  { id: "p03", n: 3, nombre: "Concha de perla grande", eje: "largo", mm: 45, tono: "perla", cat: "Mar", img: "img/charms/concha-de-perla-grande-perla.webp", proporcion: 1.007 },
  { id: "p04", n: 4, nombre: "Concha clavígera", eje: "largo", mm: 25, tono: "perla", cat: "Mar", img: "img/charms/concha-clavigera-perla.webp", proporcion: 0.71 },
  { id: "p05", n: 5, nombre: "Caracola pequeña", eje: "largo", mm: 15, tono: "perla", cat: "Mar", img: "img/charms/caracola-pequena-perla.webp", proporcion: 0.7 },
  { id: "p06", n: 6, nombre: "Piedra ovalada azul cielo", eje: "largo", mm: 15, tono: "turquesa", cat: "Piedras", img: "img/charms/piedra-ovalada-azul-cielo-turquesa.webp", proporcion: 0.683 },
  { id: "p07", n: 7, nombre: "Concha de perla chica", eje: "largo", mm: 18, tono: "perla", cat: "Mar", img: "img/charms/concha-de-perla-chica-perla.webp", proporcion: 0.867 },
  { id: "p08", n: 8, nombre: "Mano", eje: "largo", mm: 25, tono: "plata", cat: "Figuras", img: "img/charms/mano-plata.webp", proporcion: 0.493 },
  { id: "p09", n: 9, nombre: "Aleta", eje: "largo", mm: 20, tono: "oro", cat: "Mar", img: "img/charms/aleta-oro.webp", proporcion: 0.597 },
  { id: "p10", n: 10, nombre: "Naipes", eje: "largo", mm: 13, tono: "esmalte", cat: "Figuras", img: "img/charms/naipes-esmalte.webp", proporcion: 0.71 },
  { id: "p11", n: 11, nombre: "Corazón I", eje: "largo", mm: 25, tono: "rojo", cat: "Corazones", img: "img/charms/corazon-i-rojo.webp", proporcion: 0.453 },
  { id: "p12", n: 12, nombre: "Corazón II", eje: "largo", mm: 25, tono: "rojo", cat: "Corazones", img: "img/charms/corazon-ii-rojo.webp", proporcion: 0.44 },
  { id: "p13", n: 13, nombre: "Cabeza de buey", eje: "largo", mm: 20, tono: "oro", cat: "Figuras", img: "img/charms/cabeza-de-buey-oro.webp", proporcion: 1 },
  { id: "p14", n: 14, nombre: "Tejana en oro", eje: "largo", mm: 20, tono: "oro", cat: "Figuras", img: "img/charms/tejana-en-oro-oro.webp", proporcion: 0.56 },
  { id: "p15", n: 14, nombre: "Tejana en plata", eje: "largo", mm: 20, tono: "plata", cat: "Figuras", img: "img/charms/tejana-en-plata-plata.webp", proporcion: 0.62 },
  { id: "p16", n: 15, nombre: "Concha cauri con detalle", eje: "largo", mm: 20, tono: "oro", cat: "Mar", img: "img/charms/concha-cauri-con-detalle-oro.webp", proporcion: 0.877 },
  { id: "p17", n: 16, nombre: "Estrella dorada o plateada mini dorada", eje: "largo", mm: 10, tono: "oro", cat: "Estrellas", img: "img/charms/estrella-dorada-o-plateada-mini-dorada-oro.webp", proporcion: 1.024 },
  { id: "p18", n: 16, nombre: "Estrella dorada o plateada mini plateada", eje: "largo", mm: 10, tono: "plata", cat: "Estrellas", img: "img/charms/estrella-dorada-o-plateada-mini-plateada-plata.webp", proporcion: 1.095 },
  { id: "p19", n: 17, nombre: "Tortuga", eje: "largo", mm: 25, tono: "oro", cat: "Mar", img: "img/charms/tortuga-oro.webp", proporcion: 0.573 },
  { id: "p20", n: 18, nombre: "Concha caracola en oro", eje: "largo", mm: 30, tono: "oro", cat: "Mar", img: "img/charms/concha-caracola-en-oro-oro.webp", proporcion: 0.76 },
  { id: "p21", n: 18, nombre: "Concha caracola en plata", eje: "largo", mm: 30, tono: "plata", cat: "Mar", img: "img/charms/concha-caracola-en-plata-plata.webp", proporcion: 0.797 },
  { id: "p22", n: 19, nombre: "Estrella de mar dorada o dorada", eje: "largo", mm: 30, tono: "oro", cat: "Estrellas", img: "img/charms/estrella-de-mar-dorada-o-dorada-oro.webp", proporcion: 1.045 },
  { id: "p23", n: 19, nombre: "Estrella de mar dorada o plateada", eje: "largo", mm: 30, tono: "plata", cat: "Estrellas", img: "img/charms/estrella-de-mar-dorada-o-plateada-plata.webp", proporcion: 1.056 },
  { id: "p24", n: 20, nombre: "Estrella de mar mini dorada", eje: "largo", mm: 20, tono: "oro", cat: "Estrellas", img: "img/charms/estrella-de-mar-mini-dorada-oro.webp", proporcion: 1.024 },
  { id: "p25", n: 20, nombre: "Estrella de mar mini plateada", eje: "largo", mm: 20, tono: "plata", cat: "Estrellas", img: "img/charms/estrella-de-mar-mini-plateada-plata.webp", proporcion: 0.813 },
  { id: "p26", n: 21, nombre: "Libélula", eje: "ancho", mm: 20, tono: "plata", cat: "Figuras", img: "img/charms/libelula-plata.webp", proporcion: 1.245 },
  { id: "p27", n: 22, nombre: "Bota vaquera en oro", eje: "largo", mm: 20, tono: "oro", cat: "Figuras", img: "img/charms/bota-vaquera-en-oro-oro.webp", proporcion: 0.98 },
  { id: "p28", n: 22, nombre: "Bota vaquera en plata", eje: "largo", mm: 20, tono: "plata", cat: "Figuras", img: "img/charms/bota-vaquera-en-plata-plata.webp", proporcion: 0.88 },
  { id: "p29", n: 23, nombre: "Sol", eje: "largo", mm: 40, tono: "oro", cat: "Cielo", img: "img/charms/sol-oro.webp", proporcion: 0.893 },
  { id: "p30", n: 24, nombre: "Estrella de mar dorada grande", eje: "largo", mm: 40, tono: "oro", cat: "Estrellas", img: "img/charms/estrella-de-mar-dorada-grande-oro.webp", proporcion: 0.83 },
  { id: "p31", n: 25, nombre: "Dije corazón con letra", eje: "largo", mm: 15, tono: "negro", cat: "Corazones", img: "img/charms/dije-corazon-con-letra-negro.webp", proporcion: 0.947 },
  { id: "p32", n: 26, nombre: "Jaguar en oro", eje: "ancho", mm: 25, tono: "oro", cat: "Figuras", img: "img/charms/jaguar-en-oro-oro.webp", proporcion: 0.797 },
  { id: "p33", n: 26, nombre: "Jaguar en plata", eje: "ancho", mm: 25, tono: "plata", cat: "Figuras", img: "img/charms/jaguar-en-plata-plata.webp", proporcion: 0.95 },
  { id: "p34", n: 27, nombre: "Ala", eje: "largo", mm: 15, tono: "plata", cat: "Figuras", img: "img/charms/ala-plata.webp", proporcion: 0.363 },
  { id: "p35", n: 28, nombre: "Perlas asimétricas", eje: "largo", mm: 10, tono: "perla", cat: "Perlas", img: "img/charms/perlas-asimetricas-perla.webp", proporcion: 1.24 },
  { id: "p36", n: 29, nombre: "Bola de billar", eje: "diametro", mm: 10, tono: "negro", cat: "Figuras", img: "img/charms/bola-de-billar-negro.webp", proporcion: 0.99 },
  { id: "p37", n: 31, nombre: "Tipo cuarzo pequeño", eje: "largo", mm: 12, tono: "cuarzo", cat: "Piedras", img: "img/charms/tipo-cuarzo-pequeno-cuarzo.webp", proporcion: 1.327 },
  { id: "p38", n: 32, nombre: "Ojo turco azul", eje: "diametro", mm: 7, tono: "azul", cat: "Piedras", img: "img/charms/ojo-turco-azul-azul.webp", proporcion: 0.723 },
  { id: "p39", n: 33, nombre: "Piedras color", eje: "largo", mm: 8, tono: "oro", cat: "Piedras", img: "img/charms/piedras-color-oro.webp", proporcion: 1.364 },
  { id: "p40", n: 34, nombre: "Concha con detalle", eje: "ancho", mm: 30, tono: "oro", cat: "Mar", img: "img/charms/concha-con-detalle-oro.webp", proporcion: 0.987 },
  { id: "p41", n: 35, nombre: "Concha de río", eje: "ancho", mm: 20, tono: "cuarzo", cat: "Mar", img: "img/charms/concha-de-rio-cuarzo.webp", proporcion: 1.091 },
  { id: "p42", n: 36, nombre: "Coral blanco, rojo o café blanco", eje: "largo", mm: 60, tono: "perla", cat: "Mar", img: "img/charms/coral-blanco-rojo-o-cafe-blanco-perla.webp", proporcion: 0.817 },
  { id: "p43", n: 36, nombre: "Coral blanco, rojo o café cafe", eje: "largo", mm: 60, tono: "oro", cat: "Mar", img: "img/charms/coral-blanco-rojo-o-cafe-cafe-oro.webp", proporcion: 0.55 },
  { id: "p44", n: 36, nombre: "Coral blanco, rojo o café rojo", eje: "largo", mm: 60, tono: "rojo", cat: "Mar", img: "img/charms/coral-blanco-rojo-o-cafe-rojo-rojo.webp", proporcion: 0.59 },
  { id: "p45", n: 37, nombre: "Talavera", eje: "largo", mm: 25, tono: "azul", cat: "Piedras", img: "img/charms/talavera-azul.webp", proporcion: 1.24 },
  { id: "p46", n: 38, nombre: "Rosa", eje: "largo", mm: 30, tono: "oro", cat: "Flores", img: "img/charms/rosa-oro.webp", proporcion: 0.523 },
  { id: "p47", n: 39, nombre: "Sirena", eje: "largo", mm: 45, tono: "plata", cat: "Figuras", img: "img/charms/sirena-plata.webp", proporcion: 0.8 },
  { id: "p48", n: 41, nombre: "Cubos de colores", eje: "largo", mm: 10, tono: "azul", cat: "Piedras", img: "img/charms/cubos-de-colores-azul.webp", proporcion: 1.186 },
  { id: "p49", n: 42, nombre: "Chile rojo", eje: "largo", mm: 15, tono: "rojo", cat: "Figuras", img: "img/charms/chile-rojo-rojo.webp", proporcion: 0.53 },
  { id: "p50", n: 43, nombre: "Daga", eje: "largo", mm: 20, tono: "plata", cat: "Figuras", img: "img/charms/daga-plata.webp", proporcion: 0.467 },
  { id: "p51", n: 44, nombre: "Sol con rostro", eje: "ancho", mm: 15, tono: "oro", cat: "Cielo", img: "img/charms/sol-con-rostro-oro.webp", proporcion: 0.603 },
  { id: "p52", n: 45, nombre: "Luna", eje: "largo", mm: 20, tono: "oro", cat: "Cielo", img: "img/charms/luna-oro.webp", proporcion: 0.48 },
  { id: "p53", n: 46, nombre: "Cerillo en oro", eje: "largo", mm: 45, tono: "oro", cat: "Figuras", img: "img/charms/cerillo-en-oro-oro.webp", proporcion: 0.103 },
  { id: "p54", n: 46, nombre: "Cerillo en plata", eje: "largo", mm: 45, tono: "plata", cat: "Figuras", img: "img/charms/cerillo-en-plata-plata.webp", proporcion: 0.103 },
  { id: "p55", n: 47, nombre: "Granada", eje: "ancho", mm: 25, tono: "rojo", cat: "Figuras", img: "img/charms/granada-rojo.webp", proporcion: 0.627 },
  { id: "p56", n: 48, nombre: "Serpiente", eje: "largo", mm: 30, tono: "oro", cat: "Figuras", img: "img/charms/serpiente-oro.webp", proporcion: 0.767 },
  { id: "p57", n: 49, nombre: "Flor", eje: "largo", mm: 30, tono: "plata", cat: "Flores", img: "img/charms/flor-plata.webp", proporcion: 0.577 },
  { id: "p58", n: 50, nombre: "Pez cerámico verde", eje: "ancho", mm: 15, tono: "verde", cat: "Mar", img: "img/charms/pez-ceramico-verde-verde.webp", proporcion: 1.107 },
  { id: "p59", n: 51, nombre: "Perla asimétrica grande I", eje: "largo", mm: 25, tono: "perla", cat: "Perlas", img: "img/charms/perla-asimetrica-grande-i-perla.webp", proporcion: 0.78 },
  { id: "p60", n: 51, nombre: "Perla asimétrica grande II", eje: "largo", mm: 25, tono: "perla", cat: "Perlas", img: "img/charms/perla-asimetrica-grande-ii-perla.webp", proporcion: 0.757 },
  { id: "p61", n: 52, nombre: "Tarot en oro", eje: "largo", mm: 20, tono: "oro", cat: "Figuras", img: "img/charms/tarot-en-oro-oro.webp", proporcion: 0.55 },
  { id: "p62", n: 52, nombre: "Tarot en plata", eje: "largo", mm: 20, tono: "plata", cat: "Figuras", img: "img/charms/tarot-en-plata-plata.webp", proporcion: 0.533 },
  { id: "p63", n: 53, nombre: "Azulejo azul", eje: "largo", mm: 10, tono: "azul", cat: "Piedras", img: "img/charms/azulejo-azul-azul.webp", proporcion: 0.94 },
  { id: "p64", n: 54, nombre: "Caracola plana", eje: "largo", mm: 25, tono: "plata", cat: "Mar", img: "img/charms/caracola-plana-plata.webp", proporcion: 0.64 },
  { id: "p65", n: 55, nombre: "Cactus", eje: "largo", mm: 20, tono: "oro", cat: "Figuras", img: "img/charms/cactus-oro.webp", proporcion: 0.517 },
  { id: "p66", n: 56, nombre: "Bola de billar 2D en oro", eje: "diametro", mm: 20, tono: "oro", cat: "Figuras", img: "img/charms/bola-de-billar-2d-en-oro-oro.webp", proporcion: 0.853 },
  { id: "p67", n: 56, nombre: "Bola de billar 2D en plata", eje: "diametro", mm: 20, tono: "plata", cat: "Figuras", img: "img/charms/bola-de-billar-2d-en-plata-plata.webp", proporcion: 0.887 },
  { id: "p68", n: 57, nombre: "Herradura", eje: "largo", mm: 15, tono: "oro", cat: "Figuras", img: "img/charms/herradura-oro.webp", proporcion: 0.593 },
  { id: "p69", n: 58, nombre: "Copa de vino", eje: "largo", mm: 20, tono: "rojo", cat: "Figuras", img: "img/charms/copa-de-vino-rojo.webp", proporcion: 0.66 },
  { id: "p70", n: 59, nombre: "Concha cauri", eje: "largo", mm: 20, tono: "plata", cat: "Mar", img: "img/charms/concha-cauri-plata.webp", proporcion: 1.119 },
  { id: "p71", n: 60, nombre: "Botón de perla con diamantes", eje: "largo", mm: 30, tono: "perla", cat: "Perlas", img: "img/charms/boton-de-perla-con-diamantes-perla.webp", proporcion: 0.83 },

  /* Letras dibujadas, A-Z, en los dos tonos. 1 cm de largo como las del
     tablero. */
  { id: "LA-oro", nombre: "Letra A en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "A" },
  { id: "LB-oro", nombre: "Letra B en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "B" },
  { id: "LC-oro", nombre: "Letra C en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "C" },
  { id: "LD-oro", nombre: "Letra D en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "D" },
  { id: "LE-oro", nombre: "Letra E en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "E" },
  { id: "LF-oro", nombre: "Letra F en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "F" },
  { id: "LG-oro", nombre: "Letra G en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "G" },
  { id: "LH-oro", nombre: "Letra H en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "H" },
  { id: "LI-oro", nombre: "Letra I en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "I" },
  { id: "LJ-oro", nombre: "Letra J en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "J" },
  { id: "LK-oro", nombre: "Letra K en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "K" },
  { id: "LL-oro", nombre: "Letra L en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "L" },
  { id: "LM-oro", nombre: "Letra M en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "M" },
  { id: "LN-oro", nombre: "Letra N en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "N" },
  { id: "LO-oro", nombre: "Letra O en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "O" },
  { id: "LP-oro", nombre: "Letra P en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "P" },
  { id: "LQ-oro", nombre: "Letra Q en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "Q" },
  { id: "LR-oro", nombre: "Letra R en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "R" },
  { id: "LS-oro", nombre: "Letra S en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "S" },
  { id: "LT-oro", nombre: "Letra T en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "T" },
  { id: "LU-oro", nombre: "Letra U en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "U" },
  { id: "LV-oro", nombre: "Letra V en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "V" },
  { id: "LW-oro", nombre: "Letra W en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "W" },
  { id: "LX-oro", nombre: "Letra X en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "X" },
  { id: "LY-oro", nombre: "Letra Y en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "Y" },
  { id: "LZ-oro", nombre: "Letra Z en oro", eje: "largo", mm: 10, tono: "oro", cat: "Letras", letra: "Z" },
  { id: "LA-plata", nombre: "Letra A en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "A" },
  { id: "LB-plata", nombre: "Letra B en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "B" },
  { id: "LC-plata", nombre: "Letra C en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "C" },
  { id: "LD-plata", nombre: "Letra D en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "D" },
  { id: "LE-plata", nombre: "Letra E en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "E" },
  { id: "LF-plata", nombre: "Letra F en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "F" },
  { id: "LG-plata", nombre: "Letra G en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "G" },
  { id: "LH-plata", nombre: "Letra H en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "H" },
  { id: "LI-plata", nombre: "Letra I en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "I" },
  { id: "LJ-plata", nombre: "Letra J en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "J" },
  { id: "LK-plata", nombre: "Letra K en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "K" },
  { id: "LL-plata", nombre: "Letra L en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "L" },
  { id: "LM-plata", nombre: "Letra M en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "M" },
  { id: "LN-plata", nombre: "Letra N en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "N" },
  { id: "LO-plata", nombre: "Letra O en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "O" },
  { id: "LP-plata", nombre: "Letra P en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "P" },
  { id: "LQ-plata", nombre: "Letra Q en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "Q" },
  { id: "LR-plata", nombre: "Letra R en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "R" },
  { id: "LS-plata", nombre: "Letra S en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "S" },
  { id: "LT-plata", nombre: "Letra T en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "T" },
  { id: "LU-plata", nombre: "Letra U en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "U" },
  { id: "LV-plata", nombre: "Letra V en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "V" },
  { id: "LW-plata", nombre: "Letra W en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "W" },
  { id: "LX-plata", nombre: "Letra X en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "X" },
  { id: "LY-plata", nombre: "Letra Y en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "Y" },
  { id: "LZ-plata", nombre: "Letra Z en plata", eje: "largo", mm: 10, tono: "plata", cat: "Letras", letra: "Z" },
];
